// AUTO-GENERATED by scripts/gen-testid-registry.mjs — DO NOT EDIT.
// Run `npm run gen:testid-registry` to refresh. 11 static data-testid ids
// across the configured source trees. Tests select by these (i18n-safe), with compile-time
// typo-checking via the KnownTestId union.

export const TEST_IDS = [
  "app-header-bar",
  "app-root",
  "app-sidebar",
  "layout-drawer-close-button",
  "layout-drawer-content",
  "layout-sidebar-resize-handle",
  "module-error-fallback",
  "module-error-fallback-message",
  "module-error-fallback-reload",
  "module-error-fallback-retry",
  "settings-page-title",
] as const

/** Every static data-testid literal in the configured source trees. Derived (`${id}-row-${k}`) ids are NOT listed. */
export type KnownTestId = (typeof TEST_IDS)[number]

/** Accepts a known id (autocompleted) OR any string (for derived/template ids). */
export type TestIdLike = KnownTestId | (string & {})

const KNOWN = new Set<string>(TEST_IDS)
/** Runtime guard — true when `id` is a statically-known testid. */
export const isKnownTestId = (id: string): id is KnownTestId => KNOWN.has(id)
