/**
 * Store folder-convention enforcer + action type-gen.
 *
 * A store folder is any dir containing an `actions/` subdir. For each, this:
 *   1. ENFORCES the shape — `state.ts` + `index.ts` + `actions/` must all exist.
 *   2. FORBIDS a hand-written action map — `index.ts` must register actions via
 *      `import.meta.glob('./actions/*.ts')`, never an inline `lazyActions: {…}`
 *      or `actions: {…}` object. (This is what stops a future agent adding an
 *      eager/unregistered action.)
 *   3. GENERATES `actions.gen.ts` — the typed name→factory map the store passes
 *      as `defineStore`'s `AM` generic (the glob is untyped at runtime, so the
 *      types come from here). `_`-prefixed files are internal helpers, skipped.
 *
 *   node store-actions.mjs --root=src --root=../desktop/ui/src           # generate
 *   node store-actions.mjs --root=… --check                              # verify (CI)
 */
import fs from 'node:fs'
import path from 'node:path'
import { parseRoots } from './roots.mjs'

const ROOTS = parseRoots()
const CHECK = process.argv.includes('--check')
const SKIP = ['node_modules', 'dist', 'build', '.git']

/** Recursively find store folders — a dir that contains an `actions/` subdir plus
 *  an `index.ts` or `state.ts` (the store markers). Not tied to a `stores/`
 *  ancestor, so a store placed directly in its module is still enforced. */
function findActionDirs(dir, acc = []) {
  if (!fs.existsSync(dir)) return acc
  for (const e of fs.readdirSync(dir)) {
    const full = path.join(dir, e)
    if (!fs.statSync(full).isDirectory()) continue
    if (SKIP.includes(e)) continue
    if (
      e === 'actions' &&
      (fs.existsSync(path.join(path.dirname(full), 'index.ts')) ||
        fs.existsSync(path.join(path.dirname(full), 'state.ts')))
    )
      acc.push(path.dirname(full)) // the store folder
    else findActionDirs(full, acc)
  }
  return acc
}

const GEN_HEADER =
  '// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.\n' +
  '// Typed name→factory map for the actions/ folder. Runtime registration is\n' +
  "// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.\n\n"

function actionNames(storeDir) {
  return fs
    .readdirSync(path.join(storeDir, 'actions'))
    .filter(f => /\.ts$/.test(f) && !/\.(test|spec)\.ts$/.test(f) && !f.startsWith('_'))
    .map(f => f.replace(/\.ts$/, ''))
    .sort()
}

function genContent(names) {
  const lines = names.map(
    n => `  ${/^[A-Za-z_$][\w$]*$/.test(n) ? n : JSON.stringify(n)}: typeof import('./actions/${n}')['default']`,
  )
  return GEN_HEADER + `export type Actions = {\n${lines.join('\n')}\n}\n`
}

const problems = []
let generated = 0
for (const root of ROOTS) {
  for (const storeDir of findActionDirs(root)) {
    const rel = path.relative(process.cwd(), storeDir)
    // 1. structure
    for (const f of ['state.ts', 'index.ts'])
      if (!fs.existsSync(path.join(storeDir, f)))
        problems.push(`${rel}: missing ${f} (a store folder needs state.ts + index.ts + actions/)`)
    // 2. no hand-written map
    const idxPath = path.join(storeDir, 'index.ts')
    if (fs.existsSync(idxPath)) {
      const idx = fs.readFileSync(idxPath, 'utf8')
      if (/\blazyActions\s*:/.test(idx))
        problems.push(`${rel}/index.ts: uses \`lazyActions:\` — register via \`actions: import.meta.glob('./actions/*.ts')\` instead`)
      if (/\bactions\s*:\s*\{/.test(idx))
        problems.push(`${rel}/index.ts: inline \`actions: {…}\` map — use \`import.meta.glob('./actions/*.ts')\``)
      if (!/import\.meta\.glob\(\s*['"]\.\/actions\/\*/.test(idx))
        problems.push(`${rel}/index.ts: must register actions via \`import.meta.glob('./actions/*.ts')\``)
    }
    // 3. type-gen
    const want = genContent(actionNames(storeDir))
    const genPath = path.join(storeDir, 'actions.gen.ts')
    const have = fs.existsSync(genPath) ? fs.readFileSync(genPath, 'utf8') : ''
    if (CHECK) {
      if (have !== want) problems.push(`${rel}/actions.gen.ts is stale — run \`npm run gen:store-actions\``)
    } else if (have !== want) {
      fs.writeFileSync(genPath, want)
      generated++
    }
  }
}

if (problems.length) {
  console.error(`\n✗ store-actions: ${problems.length} problem(s):\n`)
  for (const p of problems) console.error('  ' + p)
  console.error('')
  process.exit(1)
}
console.log(
  CHECK
    ? '✓ store-actions: all store folders conform (state.ts+index.ts+actions/, glob-registered, actions.gen.ts current)'
    : `✓ store-actions: generated/updated ${generated} actions.gen.ts`,
)
