/**
 * Generated API endpoint definitions
 * Auto-generated from OpenAPI specification
 * 
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY ⚠️
 * This file is automatically generated from the OpenAPI specification generated from the server code.
 */

// =============================================================================
// TYPE DEFINITIONS
// =============================================================================

export interface CreateItemRequest {
  name: string
  kind: ItemKind
  description?: string
}

/** Carries an arbitrary JSON payload. */
export interface Envelope {
  payload: any
}

/** A stored item. */
export interface Item {
  /** Stable identifier. */
  id: string
  name: string
  kind: ItemKind
  description?: string
  tags?: string[]
  count?: number
}

export type ItemKind = 'alpha' | 'beta' | 'gamma'

export interface MessageContentDataText {
  type: 'text'
  text: string
}
export interface MessageContentDataImageUrl {
  type: 'image_url'
  image_url: string
}

/** A single content block of a chat message. */
export type MessageContentData = MessageContentDataText | MessageContentDataImageUrl

export enum Permission {
  UsersRead = 'users::read',
  ProjectsEdit = 'projects::edit',
  All = '*'
}

export type SSEExampleStream = {
  progress: Item
  done: boolean
}

// =============================================================================
// PERMISSIONS
// =============================================================================

export enum Permissions {
  ItemsCreate = 'items::create',
  ItemsRead = 'items::read'
}

export const PermissionDescriptions: Record<string, string> = {
  ItemsCreate: 'Create a new item',
  ItemsRead: 'Read items'
}

// =============================================================================
// API ENDPOINTS
// =============================================================================

// API endpoint definitions
export const ApiEndpoints = {
  'createItem': 'POST /api/items',
  'downloadBlob': 'GET /api/download',
  'getItem': 'GET /api/items/{id}',
  'listItems': 'GET /api/items'
} as const

// API endpoint parameters
export type ApiEndpointParameters = {
  'createItem': CreateItemRequest
  'downloadBlob': void
  'getItem': { id: string }
  'listItems': { kind?: string; limit?: number }
}

// API endpoint responses
export type ApiEndpointResponses = {
  'createItem': Item
  'downloadBlob': Blob
  'getItem': Item
  'listItems': Item[]
}

// Type helpers
export type ApiEndpoint = keyof typeof ApiEndpoints
export type ApiEndpointUrl = (typeof ApiEndpoints)[ApiEndpoint]

// Extract endpoint key from URL pattern
export function getEndpointKey(url: string): ApiEndpoint | undefined {
  const entries = Object.entries(ApiEndpoints) as [ApiEndpoint, string][]
  const found = entries.find(([_key, value]) => value === url)
  return found ? found[0] : undefined
}

// Get parameter type for endpoint
export type GetParameterType<K extends ApiEndpoint> = ApiEndpointParameters[K]

// Get response type for endpoint  
export type GetResponseType<K extends ApiEndpoint> = ApiEndpointResponses[K]

// Create reverse mapping from URL to endpoint key
export type UrlToEndpoint<U extends ApiEndpointUrl> = {
  [K in keyof typeof ApiEndpoints]: (typeof ApiEndpoints)[K] extends U
    ? K
    : never
}[keyof typeof ApiEndpoints]

// Helper types to get parameter and response types by URL
export type ParameterByUrl<U extends ApiEndpointUrl> =
  ApiEndpointParameters[UrlToEndpoint<U>]
export type ResponseByUrl<U extends ApiEndpointUrl> =
  ApiEndpointResponses[UrlToEndpoint<U>]

// Type-safe validation - this will cause a TypeScript error if any endpoint is missing
type ValidateParametersComplete = {
  [K in keyof typeof ApiEndpoints]: K extends keyof ApiEndpointParameters
    ? true
    : false
}

type ValidateResponsesComplete = {
  [K in keyof typeof ApiEndpoints]: K extends keyof ApiEndpointResponses
    ? true
    : false
}

// Type-safe validation - these will cause a TypeScript error if any endpoint is missing
// from Parameters or Responses. They are used for compile-time validation only.
export type { ValidateParametersComplete, ValidateResponsesComplete }
