// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  clearError: typeof import('./actions/clearError')['default']
  fetchOne: typeof import('./actions/fetchOne')['default']
  load: typeof import('./actions/load')['default']
  markAllRead: typeof import('./actions/markAllRead')['default']
  markRead: typeof import('./actions/markRead')['default']
  refreshUnread: typeof import('./actions/refreshUnread')['default']
  remove: typeof import('./actions/remove')['default']
  setPage: typeof import('./actions/setPage')['default']
  setUnreadOnly: typeof import('./actions/setUnreadOnly')['default']
}
